### ISSUE TITLE
Database model

### ISSUE THREAD

**Issue by martinsalaj** [do-team/Q-Q#1]
Table **Groups**
- **groupId**  _int (PK) autoincrement_
- **name** _string NOT NULL_
- **description** _string_
- **insertTimestamp** _datetime NOT NULL_

Table **Messages**
- **msgId** _int (PK) autoincrement_ 
- **parentMsgId** _int (FK)_
- **groupId** _int NOT NULL (FK)_
- **content** _string NOT NULL_
- **starCnt** _int NOT NULL DEFAULT(0)_
- **insertTimestamp** _datetime NOT NULL_

**Comment by martinsalaj** [comment]
Create a database named  **q-q**  and the tables with statements below.

CREATE DATABASE `q-q` /*!40100 DEFAULT CHARACTER SET utf8 */;

CREATE TABLE `groups` (
  `groupId` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(45) NOT NULL,
  `description` varchar(150) DEFAULT NULL,
  `insertTimestamp` datetime NOT NULL,
  PRIMARY KEY (`groupId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



CREATE TABLE `messages` (
  `msgId` int(11) NOT NULL AUTO_INCREMENT,
  `parentMsgId` int(11) DEFAULT NULL,
  `groupId` int(11) NOT NULL,
  `content` varchar(600) NOT NULL,
  `starCnt` int(11) DEFAULT '0',
  `insertTimestamp` datetime NOT NULL,
  PRIMARY KEY (`msgId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

**Comment by martinsalaj** [comment]
Need to modify DB model to contain Foreign keys.

**Comment by martinsalaj** [comment]
ALTER TABLE `q-q`.`messages` 
ADD INDEX `groupId_idx` (`groupId` ASC),
ADD INDEX `FK_parentMsgId_idx` (`parentMsgId` ASC);
ALTER TABLE `q-q`.`messages` 
ADD CONSTRAINT `FK_groupId`
  FOREIGN KEY (`groupId`)
  REFERENCES `q-q`.`groups` (`groupId`)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT,
ADD CONSTRAINT `FK_parentMsgId`
  FOREIGN KEY (`parentMsgId`)
  REFERENCES `q-q`.`messages` (`msgId`)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

**Comment by martinsalaj** [comment]
The database model is work in progress for now. It will be probably modified more.
Therefore @davesade doesn't need to use it at the moment and will be notified when it's finished.

**Comment by davesade** [comment]
Okay, cool with me. I'm just testing my SQL skills now with your example. When you are done, send me complete select, I will inject it.

**Comment by davesade** [comment]
Test message.

**Comment by martinsalaj** [comment]
New DB model.

CREATE TABLE `groups` (
  `groupId` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(50) NOT NULL,
  `description` varchar(200) DEFAULT NULL,
  `status` int(11) NOT NULL DEFAULT '0',
  `insertTimestamp` datetime DEFAULT NULL,
  PRIMARY KEY (`groupId`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;

CREATE TABLE `messages` (
  `msgId` int(11) NOT NULL AUTO_INCREMENT,
  `parentMsgId` int(11) DEFAULT NULL,
  `groupId` int(11) DEFAULT NULL,
  `content` varchar(600) NOT NULL,
  `likesCnt` int(11) DEFAULT NULL,
  `status` int(11) NOT NULL DEFAULT '0',
  `insertTimestamp` datetime DEFAULT NULL,
  PRIMARY KEY (`msgId`),
  KEY `FK_group_idx` (`groupId`),
  KEY `FK_parentMsg_idx` (`parentMsgId`),
  CONSTRAINT `FK_group` FOREIGN KEY (`groupId`) REFERENCES `groups` (`groupId`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `FK_parentMsg` FOREIGN KEY (`parentMsgId`) REFERENCES `messages` (`msgId`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

**Comment by davesade** [comment]
Done!
